# Generated by Django 4.2.7 on 2025-11-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(default='CC', max_length=2)),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('tipo_cuenta', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=12)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cuenta')),
            ],
        ),
    ]
